# Generated by Django 5.2.5 on 2025-08-31 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_supplier_fulfillment_alter_product_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='cod_supported',
        ),
        migrations.DeleteModel(
            name='Fulfillment',
        ),
    ]
