# Generated by Django 5.2.4 on 2025-08-30 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0001_initial'),
        ('products', '0003_product_cod_available_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dropship_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dropship.supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_sku',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
