# Generated by Django 5.2.5 on 2025-08-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SENT', 'Sent to Supplier'), ('ACCEPTED', 'Accepted by Supplier'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=12)),
                ('carrier', models.CharField(blank=True, max_length=100)),
                ('tracking_no', models.CharField(blank=True, max_length=100)),
                ('tracking_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('supports_cod', models.BooleanField(default=True)),
                ('lead_time_days', models.PositiveIntegerField(default=2)),
            ],
        ),
    ]
