# Generated by Django 5.2.5 on 2025-08-30 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropship', '0002_initial'),
        ('orders', '0002_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropship_fulfillments', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='fulfillment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropship_fulfillments', to='suppliers.supplier'),
        ),
    ]
