# Generated by Django 5.2.5 on 2025-08-30 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fulfillment',
            name='orders_fulfi_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='fulfillment',
            name='orders_fulfi_external_ref_idx',
        ),
        migrations.RenameField(
            model_name='fulfillment',
            old_name='external_ref',
            new_name='carrier',
        ),
        migrations.RenameField(
            model_name='fulfillment',
            old_name='tracking_number',
            new_name='tracking_no',
        ),
        migrations.RemoveField(
            model_name='fulfillment',
            name='message',
        ),
        migrations.RemoveField(
            model_name='fulfillment',
            name='order_item',
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_fulfillments', to='orders.order'),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='supplier_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fulfillment',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SENT', 'Sent to Supplier'), ('ACCEPTED', 'Accepted by Supplier'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=12),
        ),
        migrations.AlterField(
            model_name='fulfillment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_fulfillments', to='suppliers.supplier'),
        ),
    ]
