# Generated by Django 5.2.4 on 2025-08-30 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_cod_allowed_snapshot_order_payment_method_and_more'),
        ('products', '0005_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('placed', 'Placed with supplier'), ('confirmed', 'Supplier confirmed'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('external_ref', models.CharField(blank=True, max_length=100)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('tracking_url', models.URLField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment', to='orders.orderitem')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfillments', to='products.supplier')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='orders_fulf_status_5c519c_idx'), models.Index(fields=['external_ref'], name='orders_fulf_externa_376fcb_idx')],
            },
        ),
    ]
